# Generated by Django 3.2.5 on 2021-07-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_cart_course_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='types',
            field=models.CharField(default='not avaliable', max_length=100),
        ),
    ]
