# Generated by Django 3.2.5 on 2021-08-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_customer_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('emp_image', models.ImageField(upload_to='profilePic/')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
    ]
