# Generated by Django 3.2.5 on 2021-08-09 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20210806_0546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
