# Generated by Django 3.2.5 on 2021-08-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_userprofileimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileImages',
        ),
    ]
