# Generated by Django 3.2.5 on 2021-08-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_alter_customer_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_img',
            field=models.ImageField(default='static/img/profile1.png', upload_to='user_images'),
        ),
    ]
