# Generated by Django 3.2.5 on 2021-08-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_alter_customer_user_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intern_title', models.CharField(max_length=70)),
                ('intern_subtitle', models.CharField(max_length=70)),
                ('company_img', models.ImageField(upload_to='internship_Company')),
                ('intern_location', models.CharField(max_length=70)),
                ('intern_start_date', models.CharField(max_length=70)),
                ('intern_duration', models.CharField(max_length=70)),
                ('intern_stipen', models.IntegerField()),
                ('intern_last_date', models.CharField(max_length=70)),
                ('intern_or_part_time', models.CharField(max_length=70)),
            ],
        ),
    ]
