# Generated by Django 3.2.5 on 2021-08-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_internship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_img',
            field=models.ImageField(default='/profilePic.png', upload_to='user_images'),
        ),
    ]
