# Generated by Django 3.2.5 on 2021-08-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_coursebought_job_job_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_comp_name',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
