# Generated by Django 3.2.5 on 2021-08-20 03:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0030_buycourse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuyCourse',
            new_name='Course_which_Bought',
        ),
    ]
