# Generated by Django 3.2.5 on 2021-08-20 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0031_rename_buycourse_course_which_bought'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseBought',
        ),
    ]
